### ISSUE TITLE
Create a proper README

### ISSUE THREAD

**Issue by DonDebonair** [datadudes/athena#6]
Athena should have a proper README file explaining installation, usage, TODO etc. Also include AUTHORS and a contribution guide.

**Comment by mkrcah** [comment]
To make it more attractive, we might add a quick getting started guide to get Athena up-and-running with the most simple config. Detailed config options might be explained later.

**Comment by DonDebonair** [comment]
Totally agree! I've been moving around the different bits of the README, but it could still use some work. This also ties into #17. Ideally someone just types `athena init` or `athena bootstrap`, will get a couple of simple questions, and then the configuration is created.
